### PR TITLE
Add option preventing deletion of unrelated events

### PR DESCRIPTION
**Pull request by Rillke**
- It's unexpected that SHOW_TOS has ruled whether scheduled
  events not created by Stud.IP would be deleted or not.
- Stud.IP should not always delete events scheduled in Opencast
  by other software, e.g. the Opencast admin interface.
- By default, the new option to delete events not created by
  Stud.IP is *turned off*.
- Always delete events which have been created by Stud.IP if the
  course date can't be found in Stud.IP anymore (i.e. the date had
  been ereased).

### CODE REVIEW

**Comment by Rillke** [comment]
I noticed an edge case which may cause to deletion of events that are perfectly fine if they are scheduled in the moment the cronjob runs. Will fix that, too.

**Comment by Rillke** [comment]
* rebased
* db update renumbered

**Comment by Rillke** [comment]
@tgloeggl If you are ready to merge this, please let me know, or just rename the DB update after merge :)

It's in our production for a while and produces nice logs on every run (and only deletes those events it should).

**Comment by tgloeggl** [comment]
Das sieht gut aus, danke! Ich benenne lediglich mktime in mkdate um, das ist Stud.IP Standard

**Pull request merged**
