### PR TITLE
New oc videoeditor

### PR DESCRIPTION
**Pull request by tgloeggl**
- [ ] Check, if new editor is available (OC-Version?)

### CODE REVIEW

**Comment by Rillke** [comment]
[Docs say](https://docs.opencast.org/r/12.x/admin/modules/editor/):

> The editor is still beta. 

Please add a note to the release notes as I haven't had a look at the configuration yet. Thanks in advance.

**Comment by Rillke** [comment]
> OC-Version

Seit mindestens 9.x ist der Standalone Editor an Board, wird dort allerdings nicht mehr aktualisiert (version [2021-05-20](https://github.com/opencast/opencast/commit/68fbf7409c750bd5af3465e7593a12c83a541463)).

| OC-Version | Editor Versionen |
| --------------- | ---------------- |
| OC9            | 2021-05-20 |
| OC10         | 2022-03-22 |
| OC11*         | 2022-03-22 |
| OC12*         | 2022-06-15 |

*Erhält noch [Updates im Rahmen der _Acceptance Criteria for Patches in Different Versions_](https://docs.opencast.org/r/12.x/developer/#development-process/#acceptance-criteria-for-patches-in-different-versions).

Ich weiß nicht, ab welcher Version der Editor als vollwertiger Ersatz und frei von Kinderkrankheiten angesehen werden kann. Am besten mal @Arnei fragen, was er dazu meint.

**Comment by Arnei** [comment]
@Rillke is correct about the versions and about not updating the editor releases in older OC versions.

I'd say you can use the new editor fine in production since OC11. I'll start an internal discussion on whether we can remove the beta tag. Still, you will have to check for your institution and use cases if you can use the new editor, since it does not include every feature from the old editor.

**Comment by Rillke** [comment]
> Still, you will have to check for your institution and use cases if you can use the new editor, since it does not include every feature from the old editor.

They said, it's fine and expressed their positive delight about improved usability.

**Comment by tgloeggl** [comment]
siehe #621

**Pull request merged**
